---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lemmy-ui
  name: lemmy-ui
  namespace: lemmy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemmy-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lemmy-ui
    spec:
      containers:
      - name: lemmy-ui
        image: ghcr.io/ubergeek77/lemmy-ui:0.18.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1234
          protocol: TCP
        env:
          - name: LEMMY_UI_LEMMY_INTERNAL_HOST
            value: "lemmy:80"
          - name: LEMMY_UI_LEMMY_EXTERNAL_HOST
            value: "lemmy.webster.home"
          - name: LEMMY_HTTPS
            value: "true"
---
kind: Service
apiVersion: v1
metadata:
  name: lemmy-ui
  namespace: lemmy
spec:
  selector:
    app: lemmy-ui
  ports:
  - protocol: TCP
    port: 80
    name: tcp
    targetPort: 1234
  type: ClusterIP