---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pictrs
  name: pictrs
  namespace: lemmy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pictrs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pictrs
    spec:
      containers:
      - name: pictrs
        image: asonix/pictrs:0.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          #- name: PICTRS_OPENTELEMETRY_URL
          #  value: "http://otel:4137"
          - name: PICTRS__API_KEY
            value: lemmy
          - name: RUST_LOG
            value: debug
          - name: RUST_BACKTRACE
            value: full
          - name: PICTRS__MEDIA__VIDEO_CODEC
            value: vp9
          - name: PICTRS__MEDIA__GIF__MAX_WIDTH
            value: "256"
          - name: PICTRS__MEDIA__GIF__MAX_HEIGHT
            value: "256"
          - name: PICTRS__MEDIA__GIF__MAX_AREA
            value: "65536"
          - name: PICTRS__MEDIA__GIF__MAX_FRAME_COUNT
            value: "400"
---
kind: Service
apiVersion: v1
metadata:
  name: pictrs
  namespace: lemmy
spec:
  selector:
    app: pictrs
  ports:
  - protocol: TCP
    port: 8080
    name: tcp
    targetPort: 8080
  type: ClusterIP