---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: lemmy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
          - name: POSTGRES_USER
            value: lemmy
          - name: POSTGRES_PASSWORD
            value: lemmy
          - name: POSTGRES_DB
            value: lemmy
---
kind: Service
apiVersion: v1
metadata:
  name: lemmy-db
  namespace: lemmy
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    name: tcp
    targetPort: 5432
---
kind: Service
apiVersion: v1
metadata:
  name: lemmy-db-external
  namespace: lemmy
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    name: tcp
    targetPort: 5432
    nodePort: 30433
  type: NodePort